### PR TITLE
Try/Catch everything in the servlet filter to be safe (and a bit paranoid)

### PR DESCRIPTION
**Pull request by joeslice**
I think all the exception-causing spots have been addressed, but as we've seen with #49 and #54, unexpected exceptions cause our restful services to return a 500.

This change will make the 500's just warn and continue, strengthening the guarantee that the tracing library won't negatively impact your application in performance or otherwise.

### CODE REVIEW

**Comment by joeslice** [comment]
Hey @kristofa how do you feel about this pull request?

**Comment by kristofa** [comment]
Ok, sorry for the delay @joeslice . Good that you reminded me this one was still open.
I'll merge it.

**Comment by joeslice** [comment]
Great; thanks for merging this!

**Comment by srapp** [comment]
Hey @kristofa when are you next planning to release?  I'd like to get our services using this change.

**Comment by kristofa** [comment]
@srapp I'll try to find some time to do the release tomorrow. I think some other people are also waiting for a release, for example for #64.

**Comment by kristofa** [comment]
@srapp I made the brave release that contains this pull request. See [here for release notes](https://github.com/kristofa/brave/releases/tag/brave-2.4.2). It should become available in Maven Central shortly.

**Comment by srapp** [comment]
Awesome, thanks @kristofa !

**Pull request merged**
